name: thailand_city_data
description: Administrative division about Thailand.
version: 0.0.1
homepage: https://github.com/TranscodeGroup/tg_flutter_plugins/tree/main/packages/thailand_city_data

environment:
  sdk: '>=2.18.4 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
